owner: brianalabs
repo: upptime

sites:
  - name: brianalabs.com
    url: http://brianalabs.com
  - name: api.brianalabs.com
    url: https://api.brianalabs.com/v1/auth/me

status-website:
  cname: upptime.brianalabs.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for Briana Labs
