owner: brianalabs
repo: upptime

sites:
  - name: brianalabs.com
    url: http://brianalabs.com
  - name: api.brianalabs.com
    url: https://api.brianalabs.com/v1/auth/me
  - name: Upbit API
    url: https://api.upbit.com/v1/market/all
  - name: Bithumb API
    url: https://api.bithumb.com/public/ticker/all_krw
  - name: Coinone API
    url: https://api.coinone.co.kr/ticker?currency=all

status-website:
  cname: upptime.brianalabs.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for Briana Labs
